name: Product Server CI

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: test code
        run: ./gradlew clean test

      - name: Build with Gradle
        run: ./gradlew clean build